oa3_spec: ./openapi/openapi-v2.json # If start with http the file would be downloaded from the internet
name: opex_pagopa-gpd-upload-v2
location: West Europe
timespan: 5m # Default, a number or a timespan https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/scalar-data-types/timespan
#data_source: /subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-vnet-rg/providers/Microsoft.Network/applicationGateways/pagopa-p-app-gw
data_source: /subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-api-rg/providers/Microsoft.ApiManagement/service/pagopa-p-apim
resource_type: api-management
action_groups:
  - /subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/microsoft.insights/actionGroups/PagoPA
  - /subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-monitor-rg/providers/microsoft.insights/actionGroups/PagamentiAlert
overrides:
  base_path: "/upload/{gpd_aca}/debt-positions-service/v2"
  hosts: # Use these hosts instead of those inside the OpenApi spec
    - api.platform.pagopa.it
  endpoints:
    PUT /brokers/{broker-code}/organizations/{organization-fiscal-code}/debtpositions/file:
      response_time_threshold: 5
    POST /brokers/{broker-code}/organizations/{organization-fiscal-code}/debtpositions/file:
      response_time_threshold: 5
    DELETE /brokers/{broker-code}/organizations/{organization-fiscal-code}/debtpositions/file:
      response_time_threshold: 5
    GET /brokers/{broker-code}/organizations/{organization-fiscal-code}/debtpositions/file/{file-id}/status:
      response_time_threshold: 5
    GET /brokers/{broker-code}/organizations/{organization-fiscal-code}/debtpositions/file/{file-id}/report:
      response_time_threshold: 5
    GET /brokers/{broker-code}/organizations/{organization-fiscal-code}/debtpositions/file/{file-id}/files:
      response_time_threshold: 5