apiVersion: v2
name: pagopa-gpd-upload
description: Microservice that handles file upload of massive debt positions JSON object
type: application
version: 0.84.0
appVersion: 0.1.25-6-PAGOPA-1787-status-update
dependencies:
  - name: microservice-chart
    version: 2.8.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
