apiVersion: v2
name: pagopa-gpd-upload
description: Microservice that handles file upload of massive debt positions JSON object
type: application
version: 0.32.0
appVersion: 0.1.3-1-PAGOPA-1446-sviluppo-gpd-upload-improvement
dependencies:
  - name: microservice-chart
    version: 2.8.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
