microservice-chart:
  namespace: "gps"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-gpd-upload
    tag: "0.5.2"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /info
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /info
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
    replicas: 2 # same as HPA minReplica
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "weuprod.gps.internal.platform.pagopa.it"
    path: /pagopa-gpd-upload/(.*)
    servicePort: 8080
    proxyBodySize: 5m
    annotations: {nginx.ingress.kubernetes.io/proxy-read-timeout: '130'}
  serviceAccount:
    name: "gps-workload-identity"
  azure:
    workloadIdentityClientId: <workload-identity-client-id-set-automatically-by-gha>
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "1Gi"
      cpu: "0.25"
    limits:
      memory: "2Gi"
      cpu: "0.50"
  autoscaling:
    enable: true
    minReplica: 2
    maxReplica: 10
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
      - type: memory
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig:
    WEBSITE_SITE_NAME: 'pagopa-p-gpd-upload-service' # required to show cloud role name in application insights
    ENV: 'azure-kubernetes-prod'
    APP_LOGGING_LEVEL: 'INFO'
    DEFAULT_LOGGING_LEVEL: 'INFO'
    COSMOS_URI: "https://pagopa-p-weu-gps-cosmos-account.documents.azure.com:443/"
    DB_NAME: "gpd_db"
    CONTAINER_NAME: "gpd_upload_status"
    POST_FILE_RETRY_AFTER: '2000'
    LOG_LEVEL: "INFO"
    GPD_API_URL: "https://api.platform.pagopa.it/gpd/api/v1"
    CRON_RECOVERY_RATE: "3600s" # 1 hour
    OTEL_SERVICE_NAME: "pagopa-gpd-upload"
    OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=prod"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    OTEL_LOGS_EXPORTER: none
    OTEL_TRACES_SAMPLER: "always_on"
  envSecret:
    #    APPLICATIONINSIGHTS_CONNECTION_STRING: 'ai-p-connection-string'
    OTEL_EXPORTER_OTLP_HEADERS: elastic-apm-secret-token
    BLOB_CONNECTION_STRING: 'gpd-upload-sa-connection-string'
    COSMOS_KEY: 'gpd-upload-db-key'
    SLACK_TOKEN: 'pagopa-platform-reporter-oauth-token'
    SLACK_CHANNEL: 'pagopa-platform-alert-channel-id'
  keyvault:
    name: "pagopa-p-gps-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  canaryDelivery:
    create: false
    ingress:
      create: true
      proxyBodySize: 5m
      annotations: {nginx.ingress.kubernetes.io/proxy-read-timeout: '130'}
      canary:
        type: header
        headerName: X-Canary
        headerValue: canary
        weightPercent: 0
    service:
      create: true
    deployment:
      create: true
      image:
        repository: ghcr.io/pagopa/pagopa-gpd-upload
        tag: "0.0.0"
        pullPolicy: Always
      envConfig: {}
      envSecret: {}
monitoring-cron:
  namespace: "gps"
  schedule: "0 10 * * *"
  timeZone: "Europe/Rome"
  successfulJobsHistoryLimit: "1"
  image:
    repository: "curlimages/curl"
    tag: "latest"
    pullPolicy: "Always"
  command:
    - "curl"
    - "-k"
    - "-m"
    - "\"300\""
    - "https://weuprod.gps.internal.platform.pagopa.it/pagopa-gpd-upload/support/monitoring?fromDay=-1&toDay=-1"
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "150m"
  envSecrets:
    APPLICATIONINSIGHTS_CONNECTION_STRING: 'ai-p-connection-string'
  keyvault:
    name: "pagopa-p-gps-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  serviceAccount:
    name: "gps-workload-identity"
  azure:
    workloadIdentityClientId: "28793c44-d0fe-4c90-8c81-832a10ff86e2"
  tolerations:
    - key: dedicated
      operator: Equal
      value: "gps"
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
